name: Build LaTeX document
on:
  push:
    branches:
      - main
      - develop
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Tesi_Magistrale_Tecchia.tex
      - name: Upload Draft PDF
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-artifact@v2
        with:
          name: Draft PDF
          path: Tesi_Magistrale_Tecchia.pdf
      - name: Upload Final PDF
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: Final PDF
          path: Tesi_Magistrale_Tecchia.pdf
