name: Releases

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "index.pdf"
        bodyFile: "README.md"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
